var $CLJS = require("./cljs_env");
var $jscomp = $CLJS.$jscomp;
var COMPILED = false;
require("./cljs.core.js");
require("./quo2.foundations.colors.js");
require("./react_native.reanimated.js");
var module$shadow_js_shim_module$rn_emoji_keyboard=$CLJS.module$shadow_js_shim_module$rn_emoji_keyboard || ($CLJS.module$shadow_js_shim_module$rn_emoji_keyboard = {});
var react_native=$CLJS.react_native || ($CLJS.react_native = {});
var re_frame=$CLJS.re_frame || ($CLJS.re_frame = {});
var module$shadow_js_shim_module$react=$CLJS.module$shadow_js_shim_module$react || ($CLJS.module$shadow_js_shim_module$react = {});
var quo2=$CLJS.quo2 || ($CLJS.quo2 = {});
var module$shadow_js_shim_module$react_native_haptic_feedback=$CLJS.module$shadow_js_shim_module$react_native_haptic_feedback || ($CLJS.module$shadow_js_shim_module$react_native_haptic_feedback = {});
var module$shadow_js_shim_module$react_native_reanimated=$CLJS.module$shadow_js_shim_module$react_native_reanimated || ($CLJS.module$shadow_js_shim_module$react_native_reanimated = {});
var clojure=$CLJS.clojure || ($CLJS.clojure = {});
var module$shadow_js_shim_module$$react_native_community$masked_view=$CLJS.module$shadow_js_shim_module$$react_native_community$masked_view || ($CLJS.module$shadow_js_shim_module$$react_native_community$masked_view = {});
var module$shadow_js_shim_module$react_native=$CLJS.module$shadow_js_shim_module$react_native || ($CLJS.module$shadow_js_shim_module$react_native = {});
var module$shadow_js_shim_module$react_native_background_timer=$CLJS.module$shadow_js_shim_module$react_native_background_timer || ($CLJS.module$shadow_js_shim_module$react_native_background_timer = {});
var module$shadow_js_shim_module$react_native_static_safe_area_insets=$CLJS.module$shadow_js_shim_module$react_native_static_safe_area_insets || ($CLJS.module$shadow_js_shim_module$react_native_static_safe_area_insets = {});
var cljs=$CLJS.cljs || ($CLJS.cljs = {});
var module$shadow_js_shim_module$$react_native_community$slider=$CLJS.module$shadow_js_shim_module$$react_native_community$slider || ($CLJS.module$shadow_js_shim_module$$react_native_community$slider = {});
var module$shadow_js_shim_module$$react_native_community$audio_toolkit=$CLJS.module$shadow_js_shim_module$$react_native_community$audio_toolkit || ($CLJS.module$shadow_js_shim_module$$react_native_community$audio_toolkit = {});
var shadow=$CLJS.shadow || ($CLJS.shadow = {});
var native_module=$CLJS.native_module || ($CLJS.native_module = {});
var module$shadow_js_shim_module$$react_native_community$clipboard=$CLJS.module$shadow_js_shim_module$$react_native_community$clipboard || ($CLJS.module$shadow_js_shim_module$$react_native_community$clipboard = {});
var goog=$CLJS.goog || ($CLJS.goog = {});
var module$shadow_js_shim_module$react_native_fast_image=$CLJS.module$shadow_js_shim_module$react_native_fast_image || ($CLJS.module$shadow_js_shim_module$react_native_fast_image = {});
var oops=$CLJS.oops || ($CLJS.oops = {});
var module$shadow_js_shim_module$react_native_hole_view=$CLJS.module$shadow_js_shim_module$react_native_hole_view || ($CLJS.module$shadow_js_shim_module$react_native_hole_view = {});
var module$shadow_js_shim_module$react_native_linear_gradient=$CLJS.module$shadow_js_shim_module$react_native_linear_gradient || ($CLJS.module$shadow_js_shim_module$react_native_linear_gradient = {});
var reagent=$CLJS.reagent || ($CLJS.reagent = {});
var module$shadow_js_shim_module$$react_native_community$hooks=$CLJS.module$shadow_js_shim_module$$react_native_community$hooks || ($CLJS.module$shadow_js_shim_module$$react_native_community$hooks = {});
var module$shadow_js_shim_module$react_native_draggable_flatlist=$CLJS.module$shadow_js_shim_module$react_native_draggable_flatlist || ($CLJS.module$shadow_js_shim_module$react_native_draggable_flatlist = {});
var status_im=$CLJS.status_im || ($CLJS.status_im = {});
var module$shadow_js_shim_module$react_native_redash=$CLJS.module$shadow_js_shim_module$react_native_redash || ($CLJS.module$shadow_js_shim_module$react_native_redash = {});
var taoensso=$CLJS.taoensso || ($CLJS.taoensso = {});
var module$shadow_js_shim_module$$react_native_community$blur=$CLJS.module$shadow_js_shim_module$$react_native_community$blur || ($CLJS.module$shadow_js_shim_module$$react_native_community$blur = {});
var quo=$CLJS.quo || ($CLJS.quo = {});
var cljs_bean=$CLJS.cljs_bean || ($CLJS.cljs_bean = {});
var module$shadow_js_shim_module$react_native_navigation=$CLJS.module$shadow_js_shim_module$react_native_navigation || ($CLJS.module$shadow_js_shim_module$react_native_navigation = {});
var module$shadow_js_shim_module$react_native_image_crop_picker=$CLJS.module$shadow_js_shim_module$react_native_image_crop_picker || ($CLJS.module$shadow_js_shim_module$react_native_image_crop_picker = {});
var module$shadow_js_shim_module$i18n_js=$CLJS.module$shadow_js_shim_module$i18n_js || ($CLJS.module$shadow_js_shim_module$i18n_js = {});
var module$shadow_js_shim_module$react_native_gesture_handler=$CLJS.module$shadow_js_shim_module$react_native_gesture_handler || ($CLJS.module$shadow_js_shim_module$react_native_gesture_handler = {});
var utils=$CLJS.utils || ($CLJS.utils = {});
var module$shadow_js_shim_module$react_native_redash$lib$module$v1=$CLJS.module$shadow_js_shim_module$react_native_redash$lib$module$v1 || ($CLJS.module$shadow_js_shim_module$react_native_redash$lib$module$v1 = {});
var module$shadow_js_shim_module$react_native_svg=$CLJS.module$shadow_js_shim_module$react_native_svg || ($CLJS.module$shadow_js_shim_module$react_native_svg = {});

$CLJS.SHADOW_ENV.setLoaded("quo2.components.record_audio.record_audio.style.js");

goog.provide('quo2.components.record_audio.record_audio.style');
quo2.components.record_audio.record_audio.style.animated_circle = (function quo2$components$record_audio$record_audio$style$animated_circle(scale,opacity,color){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"transform","transform",1381301764),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"scale","scale",-230427353),scale], null)], null),new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"width","width",-384071477),new cljs.core.Keyword(null,"border-width","border-width",-1512605390),new cljs.core.Keyword(null,"z-index","z-index",1892827090),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"border-color","border-color",-2059162761),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),new cljs.core.Keyword(null,"height","height",1025178622)],[new cljs.core.Keyword(null,"center","center",-748944368),(56),(1),(0),new cljs.core.Keyword(null,"center","center",-748944368),color,new cljs.core.Keyword(null,"absolute","absolute",1655386478),(28),(56)]));
});
quo2.components.record_audio.record_audio.style.record_button_big_container = (function quo2$components$record_audio$record_audio$style$record_button_big_container(translate_x,translate_y,opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"transform","transform",1381301764),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"translateY","translateY",1140534123),translate_y], null),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"translateX","translateX",319703152),translate_x], null)], null),new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),new cljs.core.PersistentArrayMap(null, 8, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"bottom","bottom",-1550509018),(0),new cljs.core.Keyword(null,"right","right",-452581833),(0),new cljs.core.Keyword(null,"width","width",-384071477),(96),new cljs.core.Keyword(null,"height","height",1025178622),(96),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"z-index","z-index",1892827090),(0)], null));
});
quo2.components.record_audio.record_audio.style.record_button_big_body = (function quo2$components$record_audio$record_audio$style$record_button_big_body(button_color){
return new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"width","width",-384071477),(56),new cljs.core.Keyword(null,"height","height",1025178622),(56),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),(28),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"background-color","background-color",570434026),button_color,new cljs.core.Keyword(null,"overflow","overflow",2058931880),new cljs.core.Keyword(null,"hidden","hidden",-312506092)], null);
});
quo2.components.record_audio.record_audio.style.record_button_big_red_overlay = (function quo2$components$record_audio$record_audio$style$record_button_big_red_overlay(red_overlay_opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"opacity","opacity",397153780),red_overlay_opacity], null),new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"top","top",-1856271961),(0),new cljs.core.Keyword(null,"left","left",-399115937),(0),new cljs.core.Keyword(null,"right","right",-452581833),(0),new cljs.core.Keyword(null,"bottom","bottom",-1550509018),(0),new cljs.core.Keyword(null,"background-color","background-color",570434026),quo2.foundations.colors.danger_50], null));
});
quo2.components.record_audio.record_audio.style.record_button_big_gray_overlay = (function quo2$components$record_audio$record_audio$style$record_button_big_gray_overlay(gray_overlay_opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"opacity","opacity",397153780),gray_overlay_opacity], null),new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"top","top",-1856271961),(0),new cljs.core.Keyword(null,"left","left",-399115937),(0),new cljs.core.Keyword(null,"right","right",-452581833),(0),new cljs.core.Keyword(null,"bottom","bottom",-1550509018),(0),new cljs.core.Keyword(null,"background-color","background-color",570434026),quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.neutral_80_opa_5_opaque,quo2.foundations.colors.neutral_80)], null));
});
quo2.components.record_audio.record_audio.style.record_button_big_icon_container = (function quo2$components$record_audio$record_audio$style$record_button_big_icon_container(icon_opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"opacity","opacity",397153780),icon_opacity], null),cljs.core.PersistentArrayMap.EMPTY);
});
quo2.components.record_audio.record_audio.style.stop_icon = new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"width","width",-384071477),(13),new cljs.core.Keyword(null,"height","height",1025178622),(13),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),(4),new cljs.core.Keyword(null,"background-color","background-color",570434026),quo2.foundations.colors.white], null);
quo2.components.record_audio.record_audio.style.send_button_container = (function quo2$components$record_audio$record_audio$style$send_button_container(opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"width","width",-384071477),(56),new cljs.core.Keyword(null,"height","height",1025178622),(56),new cljs.core.Keyword(null,"top","top",-1856271961),(0),new cljs.core.Keyword(null,"right","right",-452581833),(20)], null));
});
quo2.components.record_audio.record_audio.style.send_button_connector = (function quo2$components$record_audio$record_audio$style$send_button_connector(opacity,width,height,border_radius_first_half,border_radius_second_half){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity,new cljs.core.Keyword(null,"width","width",-384071477),width,new cljs.core.Keyword(null,"height","height",1025178622),height,new cljs.core.Keyword(null,"border-bottom-left-radius","border-bottom-left-radius",-76446610),border_radius_second_half,new cljs.core.Keyword(null,"border-top-left-radius","border-top-left-radius",1361811342),border_radius_first_half,new cljs.core.Keyword(null,"border-top-right-radius","border-top-right-radius",1678770792),border_radius_first_half,new cljs.core.Keyword(null,"border-bottom-right-radius","border-bottom-right-radius",414899772),border_radius_second_half], null),new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-self","align-self",1475936794),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"background-color","background-color",570434026),quo2.foundations.colors.primary_50,new cljs.core.Keyword(null,"z-index","z-index",1892827090),(0)], null));
});
quo2.components.record_audio.record_audio.style.send_button = (function quo2$components$record_audio$record_audio$style$send_button(translate_y,opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"transform","transform",1381301764),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"translateY","translateY",1140534123),translate_y], null)], null),new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"top","top",-1856271961),new cljs.core.Keyword(null,"background-color","background-color",570434026),new cljs.core.Keyword(null,"width","width",-384071477),new cljs.core.Keyword(null,"z-index","z-index",1892827090),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"right","right",-452581833),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),new cljs.core.Keyword(null,"height","height",1025178622)],[new cljs.core.Keyword(null,"center","center",-748944368),(0),quo2.foundations.colors.primary_50,(32),(10),new cljs.core.Keyword(null,"center","center",-748944368),(32),new cljs.core.Keyword(null,"absolute","absolute",1655386478),(16),(32)]));
});
quo2.components.record_audio.record_audio.style.send_icon_container = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"z-index","z-index",1892827090),(10)], null);
quo2.components.record_audio.record_audio.style.lock_button_container = (function quo2$components$record_audio$record_audio$style$lock_button_container(opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),new cljs.core.PersistentArrayMap(null, 8, [new cljs.core.Keyword(null,"transform","transform",1381301764),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"rotate","rotate",152705015),"45deg"], null)], null),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"width","width",-384071477),(56),new cljs.core.Keyword(null,"height","height",1025178622),(56),new cljs.core.Keyword(null,"top","top",-1856271961),(20),new cljs.core.Keyword(null,"left","left",-399115937),(20)], null));
});
quo2.components.record_audio.record_audio.style.lock_button_connector = (function quo2$components$record_audio$record_audio$style$lock_button_connector(opacity,width,height,border_radius_first_half,border_radius_second_half){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity,new cljs.core.Keyword(null,"width","width",-384071477),width,new cljs.core.Keyword(null,"height","height",1025178622),height,new cljs.core.Keyword(null,"border-bottom-left-radius","border-bottom-left-radius",-76446610),border_radius_first_half,new cljs.core.Keyword(null,"border-top-left-radius","border-top-left-radius",1361811342),border_radius_first_half,new cljs.core.Keyword(null,"border-top-right-radius","border-top-right-radius",1678770792),border_radius_second_half,new cljs.core.Keyword(null,"border-bottom-right-radius","border-bottom-right-radius",414899772),border_radius_second_half], null),new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-self","align-self",1475936794),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"background-color","background-color",570434026),quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.neutral_80_opa_5_opaque,quo2.foundations.colors.neutral_80),new cljs.core.Keyword(null,"overflow","overflow",2058931880),new cljs.core.Keyword(null,"hidden","hidden",-312506092)], null));
});
quo2.components.record_audio.record_audio.style.lock_button = (function quo2$components$record_audio$record_audio$style$lock_button(translate_x_y,opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"transform","transform",1381301764),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"translateX","translateX",319703152),translate_x_y], null),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"translateY","translateY",1140534123),translate_x_y], null)], null),new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"top","top",-1856271961),new cljs.core.Keyword(null,"overflow","overflow",2058931880),new cljs.core.Keyword(null,"background-color","background-color",570434026),new cljs.core.Keyword(null,"width","width",-384071477),new cljs.core.Keyword(null,"z-index","z-index",1892827090),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),new cljs.core.Keyword(null,"height","height",1025178622),new cljs.core.Keyword(null,"left","left",-399115937)],[new cljs.core.Keyword(null,"center","center",-748944368),(24),new cljs.core.Keyword(null,"hidden","hidden",-312506092),quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.neutral_80_opa_5_opaque,quo2.foundations.colors.neutral_80),(32),(12),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"absolute","absolute",1655386478),(16),(32),(24)]));
});
quo2.components.record_audio.record_audio.style.delete_button_container = (function quo2$components$record_audio$record_audio$style$delete_button_container(opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"width","width",-384071477),(56),new cljs.core.Keyword(null,"height","height",1025178622),(56),new cljs.core.Keyword(null,"bottom","bottom",-1550509018),(20),new cljs.core.Keyword(null,"left","left",-399115937),(0)], null));
});
quo2.components.record_audio.record_audio.style.delete_button_connector = (function quo2$components$record_audio$record_audio$style$delete_button_connector(opacity,width,height,border_radius_first_half,border_radius_second_half){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity,new cljs.core.Keyword(null,"width","width",-384071477),width,new cljs.core.Keyword(null,"height","height",1025178622),height,new cljs.core.Keyword(null,"border-bottom-left-radius","border-bottom-left-radius",-76446610),border_radius_first_half,new cljs.core.Keyword(null,"border-top-left-radius","border-top-left-radius",1361811342),border_radius_first_half,new cljs.core.Keyword(null,"border-top-right-radius","border-top-right-radius",1678770792),border_radius_second_half,new cljs.core.Keyword(null,"border-bottom-right-radius","border-bottom-right-radius",414899772),border_radius_second_half], null),new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"align-self","align-self",1475936794),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"background-color","background-color",570434026),quo2.foundations.colors.danger_50,new cljs.core.Keyword(null,"z-index","z-index",1892827090),(0)], null));
});
quo2.components.record_audio.record_audio.style.delete_button = (function quo2$components$record_audio$record_audio$style$delete_button(scale,translate_x,opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"transform","transform",1381301764),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"translateX","translateX",319703152),translate_x], null),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"scale","scale",-230427353),scale], null)], null),new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"top","top",-1856271961),new cljs.core.Keyword(null,"background-color","background-color",570434026),new cljs.core.Keyword(null,"width","width",-384071477),new cljs.core.Keyword(null,"z-index","z-index",1892827090),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),new cljs.core.Keyword(null,"height","height",1025178622),new cljs.core.Keyword(null,"left","left",-399115937)],[new cljs.core.Keyword(null,"center","center",-748944368),(76),quo2.foundations.colors.danger_50,(32),(11),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"absolute","absolute",1655386478),(16),(32),(0)]));
});
quo2.components.record_audio.record_audio.style.record_button_container = (function quo2$components$record_audio$record_audio$style$record_button_container(opacity){
return react_native.reanimated.apply_animations_to_style.call(null,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"opacity","opacity",397153780),opacity], null),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),(32),new cljs.core.Keyword(null,"margin-right","margin-right",809689658),(32)], null));
});
quo2.components.record_audio.record_audio.style.button_container = new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"width","width",-384071477),(140),new cljs.core.Keyword(null,"height","height",1025178622),(140),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"flex-end","flex-end",297207970),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"flex-end","flex-end",297207970),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"right","right",-452581833),(-10)], null);
quo2.components.record_audio.record_audio.style.bar_container = new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"flex","flex",-1425124628),(1),new cljs.core.Keyword(null,"height","height",1025178622),(128)], null);
quo2.components.record_audio.record_audio.style.recording_bar_container = (function quo2$components$record_audio$record_audio$style$recording_bar_container(){
return new cljs.core.PersistentArrayMap(null, 8, [new cljs.core.Keyword(null,"height","height",1025178622),(4),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),(2),new cljs.core.Keyword(null,"background-color","background-color",570434026),quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.neutral_20,quo2.foundations.colors.neutral_80),new cljs.core.Keyword(null,"overflow","overflow",2058931880),new cljs.core.Keyword(null,"hidden","hidden",-312506092),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"left","left",-399115937),(80),new cljs.core.Keyword(null,"right","right",-452581833),(148),new cljs.core.Keyword(null,"bottom","bottom",-1550509018),(34)], null);
});
quo2.components.record_audio.record_audio.style.recording_bar = (function quo2$components$record_audio$record_audio$style$recording_bar(fill_percentage,ready_to_delete_QMARK_){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"width","width",-384071477),[cljs.core.str.cljs$core$IFn$_invoke$arity$1(fill_percentage),"%"].join(''),new cljs.core.Keyword(null,"height","height",1025178622),(4),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),(2),new cljs.core.Keyword(null,"background-color","background-color",570434026),(cljs.core.truth_(ready_to_delete_QMARK_)?quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.danger_50,quo2.foundations.colors.danger_60):quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.primary_50,quo2.foundations.colors.primary_60))], null);
});
quo2.components.record_audio.record_audio.style.timer_container = (function quo2$components$record_audio$record_audio$style$timer_container(reviewing_audio_QMARK_){
return new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"left","left",-399115937),(cljs.core.truth_(reviewing_audio_QMARK_)?(67):(20)),new cljs.core.Keyword(null,"bottom","bottom",-1550509018),28.5,new cljs.core.Keyword(null,"flex-direction","flex-direction",364609438),new cljs.core.Keyword(null,"row","row",-570139521),new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"center","center",-748944368)], null);
});
quo2.components.record_audio.record_audio.style.timer_circle = (function quo2$components$record_audio$record_audio$style$timer_circle(){
return new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"width","width",-384071477),(8),new cljs.core.Keyword(null,"height","height",1025178622),(8),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),(4),new cljs.core.Keyword(null,"margin-right","margin-right",809689658),(6),new cljs.core.Keyword(null,"background-color","background-color",570434026),quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.danger_50,quo2.foundations.colors.danger_60)], null);
});
quo2.components.record_audio.record_audio.style.timer_text = (function quo2$components$record_audio$record_audio$style$timer_text(){
return new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"color","color",1011675173),quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.danger_50,quo2.foundations.colors.danger_60)], null);
});
quo2.components.record_audio.record_audio.style.play_button = (function quo2$components$record_audio$record_audio$style$play_button(){
return cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"align-items","align-items",-267946462),new cljs.core.Keyword(null,"bottom","bottom",-1550509018),new cljs.core.Keyword(null,"background-color","background-color",570434026),new cljs.core.Keyword(null,"width","width",-384071477),new cljs.core.Keyword(null,"justify-content","justify-content",-1990475787),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"border-radius","border-radius",419594011),new cljs.core.Keyword(null,"height","height",1025178622),new cljs.core.Keyword(null,"left","left",-399115937)],[new cljs.core.Keyword(null,"center","center",-748944368),(20),quo2.foundations.colors.theme_colors.call(null,quo2.foundations.colors.neutral_10,quo2.foundations.colors.neutral_90),(32),new cljs.core.Keyword(null,"center","center",-748944368),new cljs.core.Keyword(null,"absolute","absolute",1655386478),(16),(32),(20)]);
});
Object.defineProperty(module.exports, "record_button_big_body", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.record_button_big_body; } });
Object.defineProperty(module.exports, "record_button_big_red_overlay", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.record_button_big_red_overlay; } });
Object.defineProperty(module.exports, "lock_button", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.lock_button; } });
Object.defineProperty(module.exports, "send_button_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.send_button_container; } });
Object.defineProperty(module.exports, "button_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.button_container; } });
Object.defineProperty(module.exports, "bar_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.bar_container; } });
Object.defineProperty(module.exports, "record_button_big_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.record_button_big_container; } });
Object.defineProperty(module.exports, "record_button_big_gray_overlay", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.record_button_big_gray_overlay; } });
Object.defineProperty(module.exports, "recording_bar_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.recording_bar_container; } });
Object.defineProperty(module.exports, "record_button_big_icon_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.record_button_big_icon_container; } });
Object.defineProperty(module.exports, "play_button", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.play_button; } });
Object.defineProperty(module.exports, "timer_text", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.timer_text; } });
Object.defineProperty(module.exports, "delete_button_connector", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.delete_button_connector; } });
Object.defineProperty(module.exports, "send_button", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.send_button; } });
Object.defineProperty(module.exports, "stop_icon", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.stop_icon; } });
Object.defineProperty(module.exports, "timer_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.timer_container; } });
Object.defineProperty(module.exports, "animated_circle", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.animated_circle; } });
Object.defineProperty(module.exports, "record_button_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.record_button_container; } });
Object.defineProperty(module.exports, "lock_button_connector", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.lock_button_connector; } });
Object.defineProperty(module.exports, "lock_button_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.lock_button_container; } });
Object.defineProperty(module.exports, "recording_bar", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.recording_bar; } });
Object.defineProperty(module.exports, "delete_button_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.delete_button_container; } });
Object.defineProperty(module.exports, "timer_circle", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.timer_circle; } });
Object.defineProperty(module.exports, "delete_button", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.delete_button; } });
Object.defineProperty(module.exports, "send_button_connector", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.send_button_connector; } });
Object.defineProperty(module.exports, "send_icon_container", { enumerable: false, get: function() { return quo2.components.record_audio.record_audio.style.send_icon_container; } });
//# sourceMappingURL=quo2.components.record_audio.record_audio.style.js.map
